---
title: "Top 5000 Most Variable Peaks in Distal and Intergenic Regions"
author: "Victoria Flanary and Brianna A. Jones"
date: "2024-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up the workspace
```{r set working directory and here path}
library(here)
```

```{r load packages}
library(readr)
library(dplyr)
library(data.table)
library(matrixStats)
library(circlize)
library(RColorBrewer)
library(ComplexHeatmap)
```

```{r load data}
distal_fpkm <- read_csv(here("dat", "atac-seq", "combined", "counts",
                             "distal_regions_fpkm_counts.csv")) %>% as.data.frame()
```

```{r load metadata}
metadata <- read_csv(here("doc", "atac-seq", "combined", "metadata_with_clusters.csv"))
```

# Format data
```{r move fragment names to rownames and rename columns}
rownames(distal_fpkm) <- distal_fpkm$fragments
distal_fpkm <- distal_fpkm[, -1]
colnames(distal_fpkm) <- metadata$cell_line
```

```{r save as table}
write.table(distal_fpkm, here("dat", "atac-seq", "combined", "counts", 
                              "distal_regions_fpkm_counts.table"))
```

```{r filter counts by row mean and variance}
matrix <- distal_fpkm %>% as.matrix()
row_var <- rowVars(matrix)
row_mean <- rowMeans(matrix)
filt_matrix <- subset(matrix, row_var >=1 & row_mean >= 1)
```

```{r filter again by row variance}
filt_row_var <- rowVars(filt_matrix)
```

```{r select top 5000 most variable peaks}
df <- as.data.frame(filt_matrix)
colnames(df) <- metadata$Run  # slice cannot handle duplicate colnames
top_5000 <- slice_max(df, n = 5000, order_by = filt_row_var)
```

```{r scale data}
top_5000_scaled <- t(scale(t(top_5000)))
```

```{r format data by cell line and cluster}
# arrange scaled data by cluster
metadata <- arrange(metadata, cluster)
top_5000_scaled <- top_5000_scaled[,match(metadata$Run, colnames(top_5000_scaled))]

# change column names back to the cell line names
colnames(top_5000_scaled) <- metadata$cell_line
```

```{r plot top 5000 peaks on heatmap}
# get consistent colors by setting a seed (also seems to determine colors?)
set.seed(4)

# define color palettes
heatmap_pal <- colorRamp2(c(-5, 0, 5), c("blue", "white", "red"))

cluster <- paste0("c", 1:6)
cluster_col <- brewer.pal(6, "Dark2")  # palette not used in plot
anno_pal <- list("Group" = setNames(cluster_col, cluster))

# heatmap annotation
anno <- HeatmapAnnotation(annotation_name_gp = gpar(fontsize = 12),
                          col = anno_pal, simple_anno_size = unit(3, "mm"),
                          annotation_name_side = "left",
                          cluster = as.factor(metadata$cluster))

# plot heatmap
pdf(here("res", "atac-seq", "02_eda", "top_5000_most_variable_peaks_heatmap.pdf"))

Heatmap(top_5000_scaled, name = "scaled variance",
        show_row_names = FALSE, column_names_gp = gpar(fontsize = 12),
        cluster_columns = FALSE, top_annotation = anno, col = heatmap_pal,
        use_raster = FALSE)

dev.off()
```
